# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

import math
import threading
import time
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.temperaturecontroller import Reset_Responses, SetTargetTemperature_Responses, TemperatureControllerBase

if TYPE_CHECKING:
    from ..server import Server

DEFAULT_TARGET = 21.0


class TemperatureControllerImpl(TemperatureControllerBase):
    """Simulated controller: temperature drifts toward the target with noise."""

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._target = DEFAULT_TARGET
        self._current = DEFAULT_TARGET
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._simulate, daemon=True)

    def start(self) -> None:
        super().start()
        self.update_CurrentTemperature(self._current)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        super().stop()

    def _simulate(self) -> None:
        tick = 0
        while not self._stop.wait(2.0):
            tick += 1
            noise = 0.05 * math.sin(tick / 3) + 0.02 * math.sin(time.time())
            self._current += 0.2 * (self._target - self._current) + noise
            self.update_CurrentTemperature(round(self._current, 2))

    def get_TargetTemperature(self, *, metadata: MetadataDict) -> float:
        return self._target

    def SetTargetTemperature(
        self, TargetTemperature: float, *, metadata: MetadataDict
    ) -> SetTargetTemperature_Responses:
        self._target = TargetTemperature
        return SetTargetTemperature_Responses()

    def Reset(self, *, metadata: MetadataDict) -> Reset_Responses:
        self._target = DEFAULT_TARGET
        return Reset_Responses()
