# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.temperaturecontroller import (
    Equilibrate_Responses,
    Reset_Responses,
    SetTargetTemperature_Responses,
    TemperatureControllerBase,
)

if TYPE_CHECKING:
    from ..server import Server


class TemperatureControllerImpl(TemperatureControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Default lifetime of observable command instances. Possible values:
        # None: Command instance is valid and stored in memory until server shutdown
        # datetime.timedelta: Command instance is deleted after this duration, can be increased during command runtime
        self.Equilibrate_default_lifetime_of_execution = timedelta(minutes=30)

    def get_TargetTemperature(self, *, metadata: MetadataDict) -> float:
        raise NotImplementedError  # TODO

    def SetTargetTemperature(
        self, TargetTemperature: float, *, metadata: MetadataDict
    ) -> SetTargetTemperature_Responses:
        raise NotImplementedError  # TODO

    def Reset(self, *, metadata: MetadataDict) -> Reset_Responses:
        raise NotImplementedError  # TODO

    def Equilibrate(
        self, Duration: float, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> Equilibrate_Responses:
        # set execution status from `waiting` to `running`
        instance.begin_execution()

        raise NotImplementedError  # TODO
