# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.temperaturecontroller_impl import TemperatureControllerImpl
from .generated.temperaturecontroller import TemperatureControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        # TODO: fill in your server information
        if name is None:
            name = "Demo Thermostat"
        if description is None:
            description = "Simulated SiLA 2 temperature controller for testing the Home Assistant integration"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="DemoThermostat",
            server_version="0.1",
            server_vendor_url="https://github.com/nadim/home-assistant-sila-plugin",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.temperaturecontroller = TemperatureControllerImpl(self)
        self.set_feature_implementation(TemperatureControllerFeature, self.temperaturecontroller)
